### ISSUE TITLE
[SM-01] Tela de Categorias - Storyboard

### ISSUE THREAD

**Issue by jhennyferOliveira** [beacarlos/Spilt-Milk#1]
- [x] Adicionar cards(com label e foto)

- [x] Nav Bar( com título "Categorias")

- [x] Search bar dentro da Nav bar

- [x] Link entre card e tela de feed(Ao clicar em um card ir para o feed mostrando os posts da categoria selecionada)

**Comment by jessicaguiot** [comment]
link feito mas ainda falta refatorar o código
