### ISSUE TITLE
[SM - 02] Tela de Feed - Storyboard

### ISSUE THREAD

**Issue by hiagochagas** [beacarlos/Spilt-Milk#2]
- [x] Search Bar
- [x] Organização do Post(Texto, Imagem, Curtidas, Comentários e Bookmark)
- [x] Segmented Control(Trending, Popular e Recent?)
- [x] Criar novo post
- [x] Comentar post
- [x] Tab bar

**Comment by beacarlos** [comment]
[SM - 02] Tela de Feed - Finalizado.
